services:
  mongodb:
    image: mongo:latest
    container_name: amazon-crawler-mongodb
    ports:
      - "8888:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local